export const LOADING_PAGE = 'loading_page'
export const CHANGE_GENRE_INDEX = 'change_genre_index'
export const GET_CATEGORIES = 'get_categories'
export const GET_POPULAR_MOVIES = 'get_popular_movies'
export const GET_RANDOM_MOVIE = 'get_random_movie'
export const GET_FAVOURITE_MOVIES = 'get_favourite_movies'
export const DELETE_FAVORITE_MOVIE_LIST='delete_fav_movie'